# Pull Data Using API
```$limit allows you to pull more than the max default that opendata sets```

```Uncomment & Execute API to Updated/Redownload Data```

In [3]:
import pandas as pd
# rest of the code remains the same

# Check that the request was successful
    # Read the content of the response with pandas
df = pd.read_csv("/Users/davidpaiz-torres/dataProjects/coding_the_news/dashboard_project/datasets/2024_violations.csv")
df

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,VIOLATION CODE,...,RECORD DATE,INSPECTION TYPE,Latitude,Longitude,Community Board,Council District,Census Tract,BIN,BBL,NTA
0,50017749,KINGS KITCHEN,Manhattan,92,EAST BROADWAY,10002.0,Chinese,01/09/2024,Violations were cited in the following area(s).,02B,...,03/16/2024,Cycle Inspection / Initial Inspection,40.713765,-73.993716,103.0,1.0,800.0,1003545.0,1.002820e+09,MN27
1,50079419,GRACE'S,Manhattan,252,WEST 14 STREET,10011.0,Irish,03/12/2024,Violations were cited in the following area(s).,04L,...,03/16/2024,Cycle Inspection / Re-inspection,40.739163,-74.001169,102.0,3.0,7700.0,1011096.0,1.006180e+09,MN23
2,50145538,BEST WOK NO1,Brooklyn,3411A,AVENUE H,NaN,Chinese,02/29/2024,Violations were cited in the following area(s).,02B,...,03/16/2024,Pre-permit (Operational) / Initial Inspection,0.000000,0.000000,NaN,NaN,NaN,NaN,3.000000e+00,NaN
3,50134992,YU XIANG YUAN,Queens,14238,ROOSEVELT AVE,11354.0,Chinese,02/27/2024,Violations were cited in the following area(s).,02B,...,03/16/2024,Pre-permit (Operational) / Re-inspection,40.760673,-73.825645,407.0,20.0,85500.0,4113630.0,4.050210e+09,QN22
4,50103414,ACRE,Brooklyn,64,MESEROLE AVENUE,11222.0,Japanese,02/07/2024,Violations were cited in the following area(s).,02B,...,03/16/2024,Cycle Inspection / Initial Inspection,40.726396,-73.954771,301.0,33.0,56100.0,3065497.0,3.026170e+09,BK76
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17085,50016354,THE EMPANADA SPOT,Queens,8417,NORTHERN BLVD,11372.0,Latin American,01/12/2024,Violations were cited in the following area(s).,10F,...,03/16/2024,Cycle Inspection / Initial Inspection,40.755783,-73.883262,403.0,25.0,33700.0,4034621.0,4.014140e+09,QN28
17086,41304936,DRAM SHOP,Brooklyn,339,9 STREET,11215.0,American,02/07/2024,Violations were cited in the following area(s).,04C,...,03/16/2024,Cycle Inspection / Compliance Inspection,40.668638,-73.985195,306.0,39.0,13700.0,3022138.0,3.010050e+09,BK37
17087,50121663,TAL BAGELS,Manhattan,2446,BROADWAY,10024.0,Bagels/Pretzels,03/11/2024,Violations were cited in the following area(s).,06E,...,03/16/2024,Cycle Inspection / Re-inspection,40.791072,-73.974381,107.0,6.0,17900.0,1033556.0,1.012388e+09,MN12
17088,41250519,MILANO'S BAR,Manhattan,51,EAST HOUSTON STREET,10012.0,Bottled Beverages,01/29/2024,Violations were cited in the following area(s).,06D,...,03/16/2024,Cycle Inspection / Initial Inspection,40.724769,-73.994440,102.0,1.0,4300.0,1007921.0,1.005090e+09,MN24
17089,41280104,NO 1 LUCK SUNG RESTAURANT,Bronx,694,EAST 187 STREET,10458.0,Chinese,01/30/2024,Violations were cited in the following area(s).,28-01,...,03/16/2024,Administrative Miscellaneous / Initial Inspection,40.854167,-73.884563,206.0,15.0,39100.0,2012520.0,2.030890e+09,BX06

# Check that all rows of data are here

In [4]:
len(df)

17090

In [5]:
df.columns

Index(['CAMIS', 'DBA', 'BORO', 'BUILDING', 'STREET', 'ZIPCODE',
       'CUISINE DESCRIPTION', 'INSPECTION DATE', 'ACTION', 'VIOLATION CODE',
       'VIOLATION DESCRIPTION', 'CRITICAL FLAG', 'SCORE', 'GRADE',
       'GRADE DATE', 'RECORD DATE', 'INSPECTION TYPE', 'Latitude', 'Longitude',
       'Community Board', 'Council District', 'Census Tract', 'BIN', 'BBL',
       'NTA'],
      dtype='object')

# Set  a Variable With Certain Columns

# Call New List

In [6]:
sorted_df = df.sort_values(by="INSPECTION DATE", ascending=False)
sorted_df.head()

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,VIOLATION CODE,...,RECORD DATE,INSPECTION TYPE,Latitude,Longitude,Community Board,Council District,Census Tract,BIN,BBL,NTA
13087,50066640,FISHERMAN'S COVE,Brooklyn,4917,CHURCH AVENUE,11203.0,Caribbean,03/15/2024,Violations were cited in the following area(s).,02B,...,03/16/2024,Cycle Inspection / Re-inspection,40.651702,-73.931123,317.0,41.0,86800.0,3102092.0,3.046750e+09,BK96
2229,50066640,FISHERMAN'S COVE,Brooklyn,4917,CHURCH AVENUE,11203.0,Caribbean,03/15/2024,Violations were cited in the following area(s).,08C,...,03/16/2024,Cycle Inspection / Re-inspection,40.651702,-73.931123,317.0,41.0,86800.0,3102092.0,3.046750e+09,BK96
6933,50066640,FISHERMAN'S COVE,Brooklyn,4917,CHURCH AVENUE,11203.0,Caribbean,03/15/2024,Violations were cited in the following area(s).,02G,...,03/16/2024,Cycle Inspection / Re-inspection,40.651702,-73.931123,317.0,41.0,86800.0,3102092.0,3.046750e+09,BK96
539,50066640,FISHERMAN'S COVE,Brooklyn,4917,CHURCH AVENUE,11203.0,Caribbean,03/15/2024,Violations were cited in the following area(s).,04L,...,03/16/2024,Cycle Inspection / Re-inspection,40.651702,-73.931123,317.0,41.0,86800.0,3102092.0,3.046750e+09,BK96
16985,50066640,FISHERMAN'S COVE,Brooklyn,4917,CHURCH AVENUE,11203.0,Caribbean,03/15/2024,Violations were cited in the following area(s).,28-06,...,03/16/2024,Cycle Inspection / Re-inspection,40.651702,-73.931123,317.0,41.0,86800.0,3102092.0,3.046750e+09,BK96

In [7]:
boro_counts = df[['BORO']].value_counts().head().to_frame('Borough Counts')
boro_counts

               Borough Counts
BORO
Manhattan                6001
Brooklyn                 5032
Queens                   3721
Bronx                    1556
Staten Island             780

In [8]:
# Make sure all the data is there
boro_counts.sum()

Borough Counts    17090
dtype: int64

In [9]:
# Check unique values of each row (onoly 2 violation codes, because I filtered it to only show rat/mice related violations via google sheets)
df.nunique()

CAMIS                    4481
DBA                      3830
BORO                        5
BUILDING                 2544
STREET                   1074
ZIPCODE                   185
CUISINE DESCRIPTION        76
INSPECTION DATE            54
ACTION                      5
VIOLATION CODE             90
VIOLATION DESCRIPTION      99
CRITICAL FLAG               3
SCORE                      94
GRADE                       6
GRADE DATE                 53
RECORD DATE                 1
INSPECTION TYPE            28
Latitude                 4239
Longitude                4241
Community Board            61
Council District           51
Census Tract              907
BIN                      4056
BBL                      4068
NTA                       190
dtype: int64

In [10]:
biz_counts = pd.read_csv("/Users/davidpaiz-torres/dataProjects/coding_the_news/dashboard_project/datasets//breakdowns_by_res.csv")

# Get the counts for each Restuarant

```Re-run if data has been updated```

In [11]:
columns = ['BORO']
if all(col in df.columns for col in columns):
    res_counts = df[columns].value_counts().head().to_frame("res_counts").sort_values(by="res_counts", ascending=False)
res_counts

               res_counts
BORO
Manhattan            6001
Brooklyn             5032
Queens               3721
Bronx                1556
Staten Island         780

In [12]:
columns = ['BORO']
if all(col in df.columns for col in columns):
    res_counts = df[columns].value_counts().head().to_frame("res_counts").sort_values(by="res_counts", ascending=False)
res_counts

               res_counts
BORO
Manhattan            6001
Brooklyn             5032
Queens               3721
Bronx                1556
Staten Island         780

In [13]:
columns = ['DBA']
if all(col in df.columns for col in columns):
    res_counts = df[columns].value_counts().head().to_frame("DBA_COUNT").sort_values(by="DBA", ascending=False)
res_counts

                       DBA_COUNT
DBA
SUBWAY                       155
STARBUCKS                     74
MCDONALD'S                   137
KENNEDY FRIED CHICKEN         66
DUNKIN                       215

# Get the counts for each Violation Code

```Re-run if data has been updated```

In [14]:
df['VIOLATION CODE'].value_counts() #

VIOLATION CODE
10F      2457
08A      1480
10B      1165
06C      1075
06D      1038
         ...
19-08       1
06H         1
04I         1
02D         1
19-01       1
Name: count, Length: 90, dtype: int64

In [15]:

# percent_sentence = print(f"Violations where evidence of mice or life mice in an establishment make up nearly 4% of all violations")
# percent_sentence

# Get the counts for each Community Board

```Re-run if data has been updated```

# Define Community Board by 100s:
```Manhattan = 100```
```Bronx = 200```
```Brooklyn = 300```
```Queens = 400```
```Staten Island = 500```

In [16]:
df["VIOLATION DESCRIPTION"].unique()

array(['Hot TCS food item not held at or above 140 °F.',
       "Evidence of mice or live mice in establishment's food or non-food areas.",
       'Food Protection Certificate (FPC) not held by manager or supervisor of food operations.',
       nan, "Live roaches in facility's food or non-food area.",
       'Thawing procedure improper.',
       'Wash hands sign not posted near or above hand washing sink.',
       "Evidence of rats or live rats in establishment's food or non-food areas.",
       'Accurate thermometer not provided or properly located in refrigerated, cold storage or hot holding equipment',
       'Lighting fixture located over, by or within food storage, preparation, service or display facility, and facility where utensils and equipment are cleaned and stored, which may shatter due to extreme heat, temperature changes or accidental contact; not fitted with shatterproof bulb or shielded and encased, with end caps or other device.',
       'Filth flies or food/refuse/sewage associated with (FRSA) flies or other nuisance pests in establishment’s food and/or non-food areas. FRSA flies include house flies, blow flies, bottle flies, flesh flies, drain flies, Phorid flies and fruit flies.',
       'Dishwashing and ware washing: Cleaning and sanitizing of tableware, including dishes, utensils, and equipment deficient.',
       'Toxic chemical or pesticide improperly stored or used such that food contamination may occur.',
       'Non-food contact surface or equipment made of unacceptable material, not kept clean, or not properly sealed, raised, spaced or movable to allow accessibility for cleaning on all sides, above and underneath the unit.',
       'Raw, cooked or prepared food is adulterated, contaminated, cross-contaminated, or not discarded in accordance with HACCP plan.',
       'Design, construction, materials used or maintenance of food contact surface improper. Surface not easily cleanable, sanitized and maintained.',
       'Wiping cloths not stored clean and dry, or in a sanitizing solution, between uses.',
       'Caloric content not posted on menus, menu boards or food tags, in a food service establishment that is 1 of 15 or more outlets operating the same type of business nationally under common ownership or control, or as a franchise or doing business under the same name, for each menu item that is served in portions, the size and content of which are standardized.',
       'Pesticide not properly labeled or used by unlicensed individual. Pesticide, other toxic chemical improperly used/stored. Unprotected, unlocked bait station used.',
       'Garbage receptacle not pest or water resistant, with tight-fitting lids, and covered except while in active use. Garbage receptacle and cover not cleaned after emptying and prior to reuse. Garbage, refuse and other solid and liquid waste not collected, stored, removed and disposed of so as to prevent a nuisance.',
       'The original nutrition fact labels or ingredient label for a cooking oil, shortening or margarine or food item sold in bulk, or acceptable manufacturer’s documentation not maintained on site.',
       'Food worker/food vendor does not use utensil or other barrier to eliminate bare hand contact with food that will not receive adequate additional heat treatment.',
       'After cooking or removal from hot holding, TCS food not cooled by an approved method whereby the internal temperature is reduced from 140 °F to 70 °F or less within 2 hours, and from 70 °F to 41 °F or less within 4 additional hours.',
       'Anti-siphonage or back-flow prevention device not provided where required; equipment or floor not properly drained; sewage disposal system in disrepair or not functioning properly. Condensation or liquid waste improperly disposed of.',
       'Contract with a pest management professional not in place. Record of extermination activities not kept on premises.',
       'Establishment is not free of harborage or conditions conducive to rodents, insects or other pests.',
       'No hand washing facility in or adjacent to toilet room or within 25 feet of a food preparation, food service or ware washing area. Hand washing facility not accessible, obstructed or used for non-hand washing purposes. No hot and cold running water or water at inadequate pressure. No soap or acceptable hand-drying device.',
       'Food contact surface not properly washed, rinsed and sanitized after each use and following any activity when contamination may have occurred.',
       'Cold TCS food item held above 41 °F; smoked or processed fish held above 38 °F; intact raw eggs held above 45 °F; or reduced oxygen packaged (ROP) TCS foods held above required temperatures except during active necessary preparation.',
       'Sanitized equipment or utensil, including in-use food dispensing utensil, improperly used or stored.',
       'Single service article not provided. Single service article reused or not protected from contamination when transported, stored, dispensed. Drinking straws not completely enclosed in wrapper or dispensed from a sanitary device.',
       'Insufficient or no hot holding, cold storage or cold holding equipment provided to maintain Time/Temperature Control for Safety Foods (TCS) at required temperatures',
       'Nuisance created or allowed to exist. Facility not free from unsafe, hazardous, offensive or annoying condition.',
       'Food, prohibited, from unapproved or unknown source, home canned or home prepared. Animal slaughtered, butchered or dressed (eviscerated, skinned) in establishment. Reduced Oxygen Packaged (ROP) fish not frozen before processing. ROP food prepared on premises transported to another site.',
       'No approved written standard operating procedure for avoiding contamination by refillable returnable containers.',
       'Food, supplies, or equipment not protected from potential source of contamination during storage, preparation, transportation, display, service or from customer’s refillable, reusable container. Condiments not in single-service containers or dispensed directly by the vendor.',
       'Juice packaged on premises with no or incomplete label, no warning statement',
       'Failure to post or conspicuously post healthy eating information',
       '“Choking first aid” poster not posted. “Alcohol and Pregnancy” warning sign not posted. Resuscitation equipment: exhaled air resuscitation masks (adult & pediatric), latex gloves, sign not posted.',
       'Personal cleanliness is inadequate. Outer garment soiled with possible contaminant. Effective hair restraint not worn where required. Jewelry worn on hands or arms. Fingernail polish worn or fingernails not kept clean and trimmed.',
       'Sign prohibiting smoking or using electronic cigarettes not conspicuously posted.',
       'Toilet facility not maintained or provided with toilet paper, waste receptacle or self-closing door.',
       'Food allergy information poster not conspicuously posted where food is being prepared or processed by food workers.',
       'Tobacco or electronic cigarette use, eating, or drinking from open container in food preparation, food storage or dishwashing area.',
       'Failure to provide a single-use, non-compostable plastic straw upon request.',
       'Swollen, leaking, rusted or otherwise damaged canned food to be returned to distributor not segregated from intact product and clearly labeled DO NOT USE',
       'Food adulterated or misbranded. Adulterated or misbranded food possessed, being manufactured, produced, packed, sold, offered for sale, delivered or given away',
       'Properly scaled and calibrated thermometer or thermocouple not provided or not readily accessible in food preparation and hot/cold holding areas to measure temperatures of TCS foods during cooking, cooling, reheating, and holding.',
       'Providing single-use, non-compostable plastic straws to customers without customer request (including providing such straws at a self-serve station)',
       'Hot TCS food item that has been cooked and cooled is being held for service without first being reheated to 165º F or above within 2 hours.',
       'Mechanical or natural ventilation not provided, inadequate, improperly installed, in disrepair or fails to prevent and control excessive build-up of grease, heat, steam condensation, vapors, odors, smoke or fumes.',
       'Food worker/food vendor does not wash hands thoroughly after using the toilet, or after coughing, sneezing, smoking, eating, preparing raw foods or otherwise contaminating hands or does not change gloves when required; Worker fails to refrain from smoking or being fully clothed in clean outer garments.',
       'Sewage disposal system is not provided, improper, inadequate or unapproved.',
       'Design, construction, materials used or maintenance of food contact surface improper.  Surface not easily cleanable, sanitized and maintained.',
       'Current letter grade or Grade Pending card not posted',
       'Live animal other than fish in tank or service animal present in facility’s food or non-food area.',
       'Food contact surface, refillable, reusable containers, or equipment improperly constructed, placed or maintained. Unacceptable material used. Culinary sink or other acceptable method not provided for washing food.',
       'Meat, fish, molluscan shellfish, unpasteurized raw shell eggs, poultry or other TCS offered or served raw or undercooked and written notice not provided to consumer.',
       'Toilet facility not provided for employees or for patrons when required. Shared patron-employee toilet accessed through kitchen, food prep or storage area or utensil washing area.',
       'After cooking or removal from hot holding, TCS food not cooled by an approved method whereby the internal temperature is reduced from 140 °F to 70 °F or less within 2  hours, and from 70 °F to 41 °F or less within 4 additional hours.',
       'Lighting inadequate; permanent lighting not provided in food preparation areas, ware washing areas, and storage rooms. Shatterproof bulb or shield to prevent broken glass from falling into food or onto surfaces, not installed.',
       'Food Protection Certificate not available for inspection',
       'Food preparation area, food storage area, or other area used by employees or patrons, contaminated by sewage or liquid waste.',
       'Document issued by the Board of Health, Commissioner or Department reproduced or altered. False, untrue or misleading statement or document made to, submitted or filed with the Department',
       'Providing single-use plastic stirrers or single-use plastic splash sticks.',
       'Commercially processed pre-cooked TCS in hermetically sealed containers and precooked TCS in intact packages from non-retail food processing establishments not heated to 140 °F within 2 hours of removal from container or package.',
       'Additional nutritional information statement not posted, or additional nutritional information not provided',
       'Failure to display required signage about plastic straw availability',
       'Personal cleanliness is inadequate. Outer garment soiled with possible contaminant. Effective hair restraint not worn where required.  Jewelry is worn on hands or arms.  Fingernail polish worn or fingernails not kept clean and trimmed.',
       'TCS food removed from cold holding or prepared from or combined with ingredients at room temperature not cooled by an approved method to 41 °F or below within 4 hours.',
       'Food, supplies, and equipment not protected from potential source of contamination during storage, preparation, transportation, display or service.',
       'Harmful noxious gas or vapor detected. Carbon Monoxide (CO) level exceeds nine (9) ppm',
       'Failure to maintain a sufficient supply of single-use, non-compostable plastic straws.',
       'Shellfish not from approved source, not or improperly tagged/labeled; tags not retained for 90 days.',
       'HACCP plan not approved or approved HACCP plan not maintained on premises.',
       'Food containing a prohibited substance held, kept, offered, prepared, processed, packaged, or served.',
       'Flavored tobacco products sold, offered for sale',
       'Dishwashing and ware washing:  Cleaning and sanitizing of tableware, including dishes, utensils, and equipment deficient.',
       'Current letter grade or "Grade Pending" card not conspicuously posted or visible to passersby',
       'Time/Temperature Control for Safety (TCS) food not cooked to required minimum internal temperature.   • Poultry, poultry parts, ground and comminuted poultry, all stuffing containing poultry, meats, fish or ratites to or above 165 °F for 15 seconds with no interruption of the cooking process   • Ground meat, and food containing ground and comminuted meat, to or above 158 °F for 15 seconds with no interruption of the cooking process, except per individual customer request  • Pork, any food containing pork to or above 150 °F for 15 seconds  • Mechanically tenderized or injected meats to or above 155 °F.  • Whole meat roasts and beef steak to or above required temperature and time except per individual customer request  • Raw animal foods cooked in microwave to or above165 °F, covered, rotated or stirred   • All other foods to or above 140 °F for 15 seconds; shell eggs to or above 145 °F for 15 seconds except per individual customer request.',
       'Workplace SFAA policy not prominently posted in workplace.',
       'Food service operation occurring in room or area used as living or sleeping quarters.',
       'Equipment used for ROP not approved by the Department',
       'Non-TCS food that has been served to the public being re-served. (Does not apply to wrapped foods where the wrapper seal has not been broken or opened).',
       'Providing compostable plastic straws to be used outside of the food establishment’s premises; failure to appropriately dispose of compostable plastic straws; failure to maintain required bins for disposal of compostable plastic straws.',
       'Records and logs not maintained to show that approved HACCP plan has been properly implemented.',
       'Smoking or electronic cigarette use allowed in prohibited area',
       'Required succinct nutritional statements not posted on menu(s) for adults and children (2,000 calories per day for adults)',
       'Hot TCS food item that has been cooked and  cooled is being held for service without first being reheated to 165º F or above within 2 hours.',
       'Unclean or cracked whole eggs or unpasteurized liquid, frozen or powdered eggs kept or used.',
       'Filth flies or food/refuse/sewage associated with (FRSA) flies or other nuisance pests  in  establishment’s food and/or non-food areas. FRSA flies include house flies, blow flies, bottle flies, flesh flies, drain flies, Phorid flies and fruit flies.',
       'No or inadequate potable water supply. Water or ice not potable or from unapproved source. Bottled water not NY State certified. Cross connection in potable water supply system.',
       'Duties of an officer of the Department interfered with or obstructed.',
       'Order or notice posted or required to be posted by the Department mutilated, obstructed or removed.',
       'Original label for smoking products sold or offered for sale.',
       'A food containing artificial trans-fat, with 0.5 grams or more of trans fat per serving, is being stored, distributed, held for service, used in preparation of a menu item, or served.',
       'No hand washing facility in or adjacent to toilet room or within 25 feet of a food preparation, food service or ware washing area.  Hand washing facility not accessible, obstructed or used for non-hand washing purposes. No hot and cold running water or water at inadequate pressure. No soap or acceptable hand-drying device.',
       'Pesticide not properly labeled or used by unlicensed individual.  Pesticide, other toxic chemical improperly used/stored. Unprotected, unlocked bait station used.',
       'Food not labeled in accordance with the approved HACCP plan',
       'Organics mixed with non-organic material'], dtype=object)

In [17]:
df["DBA"].value_counts().head(10)

DBA
DUNKIN                                   215
SUBWAY                                   155
MCDONALD'S                               137
STARBUCKS                                 74
KENNEDY FRIED CHICKEN                     66
POPEYES                                   54
BURGER KING                               48
GOLDEN KRUST CARIBBEAN BAKERY & GRILL     47
DUNKIN DONUTS                             40
PARIS BAGUETTE                            40
Name: count, dtype: int64

In [39]:
df[df["VIOLATION CODE"] == "04L"][["BORO", "DBA"]].value_counts().sort_values(ascending=False)

BORO           DBA
Queens         SUBWAY                               5
Manhattan      BLUESTONE LANE                       4
Bronx          KENNEDY FRIED CHICKEN                3
Manhattan      CRUMBL                               3
Bronx          DUNKIN                               3
                                                   ..
               ANISE                                1
Staten Island  ROSEBANK PIZZA                       1
Bronx          ANDY'S TERIYAKI & TACO               1
               ADAYA AFRICAN AMERICAN RESTAURANT    1
Staten Island  WILD CRAB HOUSE                      1
Name: count, Length: 941, dtype: int64